# site settings
title: Jack Etheredge, PhD
subtitle: Data Scientist in New York City
email: jack.etheredge@gmail.com
description: Data Scientist, PhD in Developmental Biology and Neuroscience in New York City
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Jack Etheredge, PhD
street_address: 
city: New York
state: NY
zip_code: 
country: United States of America
phone: (803) 367-1152

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 8

# social settings
500px_url:
facebook_url:
github_url: https://github.com/Jack-Etheredge
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/jack-etheredge-phd/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/JackNEtheredge

# build settings
markdown: kramdown

sass:
  style: compressed
